version: '3.7'

services:
  miks:
    container_name: miks
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '4200:4200'
      - '49153:49153'
    environment:
      - CHOKIDAR_USEPOLLING=true